### ISSUE TITLE
`/models/small` dir doesn't exist

### ISSUE THREAD

**Issue by mzuzic** [abaheti95/QADialogSystem#1]
Hi, there doesn't seem to be a  `/models/small` dir when I unzip the gpt_and_dgpt_models.zip folder.

Where can I download it? Or could you provide more info on how to run the test, what is the pretrained model and the library versions.

**Comment by mzuzic** [comment]
Error that I get when loading with GPT2:

`RuntimeError: Error(s) in loading state_dict for GPT2LMHeadModel:
	Missing key(s) in state_dict: "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.masked_bias", "transformer.h.6.attn.masked_bias", "transformer.h.7.attn.masked_bias", "transformer.h.8.attn.masked_bias", "transformer.h.9.attn.masked_bias", "transformer.h.10.attn.masked_bias", "transformer.h.11.attn.masked_bias". `

**Comment by abaheti95** [comment]
Thanks for pointing this out. The model/small had DialoGPT small parameters. I compressed the required folder into [another zip file](https://mega.nz/file/IYR0RTLb#9VCLhBLVXpiexr8TJ2YDbd8MiQpdT1ViocRNNiBwWxU). Let me know if this works or if you have any other issues.

**Comment by mzuzic** [comment]
> Thanks for pointing this out. The model/small had DialoGPT small parameters. I compressed the required folder into [another zip file](https://mega.nz/file/IYR0RTLb#9VCLhBLVXpiexr8TJ2YDbd8MiQpdT1ViocRNNiBwWxU). Let me know if this works or if you have any other issues.

Thanks for the fast reply! This solves the problem.

Edit: Forgot to add, the state_dict isn't compatible with the newest version of the transformers library. `transformers==2.8.0` worked for me.
